version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  mongodb:
    image: mongo:4.2.11
    volumes:
      - ./localdev/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local